# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: 'https://beta.segundao.la'
    weight: 20
  - name: Blog
    url: 'https://blog.segundao.la'
    weight: 20
  - name: Cursos
    url: 'https://beta.segundao.la/cursos'
    weight: 20
  - name: Videos
    url: 'https://beta.segundao.la/videos'
    weight: 20
  - name: 'artistas'
    url: 'https://beta.segundao.la/artistas'
    weight: 20 

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
